-

diff --git a/exec/import-lxc b/exec/import-lxc
--- a/exec/import-lxc
+++ b/exec/import-lxc
@@ -1,151 +1,34 @@
-#!/usr/bin/env python3
+#!/bin/bash
 #
-# usage: plash import-lxc IMAGE-NAME [--dry]
+# usage: plash import-lxc DISTRO:VERSION [--dry]
 # Import image from linuxcontainers.org
 # if --dry is set, the image url is printed but not imported
 
-import re
-import os
-import sys
-from urllib.error import URLError
-from urllib.request import urlopen
+set -e
+set -o pipefail
 
-from plash import utils
-
-LXC_URL_TEMPL = "https://images.linuxcontainers.org/images/{}/{}/{}/{}/{}/rootfs.tar.xz"
-
-UBUNTU_ABC = "tuvwxyzabcdefghijklmnopqrs"  # rotate manually every decade or so
-
-DEPRECTATED_IMAGE_NAMES = {
-    # 'plamo': ... 'plamo' is really forgotten for
-    "cosmic": "ubuntu:cosmic",
-    "disco": "ubuntu:disco",
-    "edge": "alpine:edge",
-    "eoan": "ubuntu:eoan",
-    "jessie": "debian:jessie",
-    "sid": "debian:sid",
-    "stretch": "debian:stretch",
-    "trusty": "ubuntu:trusty",
-    "tumbleweed": "opensuse:tumbleweed",
-    "xenial": "ubuntu:xenial",
-}
+INDEX_URL=https://images.linuxcontainers.org/meta/1.0/index-user
 
 
-def use_current(version):
-    return int(version == "current")
+if ! [[ "$1" = *':'* ]]; then
+  echo "usage: plash import-lxc DISTRO:VERSION [--dry]" >&2
+  exit 1
+fi
 
-
-def use_version_number(version):
-    try:
-        return tuple(int(i) for i in version.split("."))
-    except ValueError:
-        return (-1,)
-
-
-def use_index(order):
-    order_lower = [i.lower() for i in order]
-
-    def quantifier(version):
-        try:
-            return order_lower.index(version.lower())
-        except ValueError:
-            return -1
-
-    return quantifier
-
-
-def use_alphabet(version):
-    return version
-
-
-def use_ubuntu(version):
-    return UBUNTU_ABC.find(version[0].lower())
-
-
-USE_NEWEST_VERSION = {
-    "alpine": use_version_number,
-    "archlinux": use_current,
-    "centos": use_version_number,
-    "debian": use_index(["jessie", "stretch", "buster", "bullseye"]),
-    "devuan": use_alphabet,
-    "fedora": use_version_number,
-    "gentoo": use_current,
-    "kali": use_current,
-    "opensuse": use_version_number,
-    "openwrt": use_current,
-    "oracle": use_version_number,
-    "sabayon": use_current,
-    "ubuntu": use_ubuntu,
-    "ubuntu-core": use_version_number,
-}
-
-utils.assert_initialized()
-
-try:
-    image_name = sys.argv[1]
-    dry_run = sys.argv[2:3] == ["--dry"]
-except IndexError:
-    utils.die_with_usage()
-
-with utils.catch_and_die([URLError]):
-    content = urlopen("https://images.linuxcontainers.org/").read().decode()
-matches = re.findall(
-    "<tr><td>(.+?)</td><td>(.+?)</td><td>(.+?)</td><td>(.+?)</td><td>(.+?)</td><td>(.+?)</td><td>(.+?)</td><td>(.+?)</td></tr>",
-    content,
+match=$(curl --silent --fail --location $INDEX_URL |
+  awk -F";" '$3 == "amd64" && $4 == "default" { print $1":"$2" "$6 }' |
+  awk -v a="$1" 'a == $1 { print $2 }'
 )
 
-versions = {}
-urls = {}
-for distro, version, arch, variant, date, _, _, _ in matches:
-    if variant != "default" or arch != "amd64":
-        continue
-    url = LXC_URL_TEMPL.format(distro, version, arch, variant, date)
-    urls[(distro, version)] = url
-    versions.setdefault(distro, [])
-    versions[distro].append(version)
+if [ -z "$match" ]; then
+  echo "plash error: no match for \"$1\" (check $INDEX_URL)" >&2
+  exit 1
+fi
 
+rootfs=https://images.linuxcontainers.org"$match"rootfs.tar.xz
 
-def die_image_not_found():
-    all_images = sorted([":".join(i) for i in urls] + list(USE_NEWEST_VERSION.keys()))
-    utils.die(
-        "image not found ({}), but there is: {}".format(
-            repr(image_name), " ".join(all_images)
-        )
-    )
-
-
-# handle eventual deprecated image
-try:
-    orig_image_name = image_name
-    image_name = DEPRECTATED_IMAGE_NAMES[image_name]
-    print(
-        "plash: rename image (due to indefinitely supported deprecation): {} -> {}".format(
-            orig_image_name, image_name
-        ),
-        file=sys.stderr,
-    )
-except KeyError:
-    pass
-
-if not ":" in image_name:
-    try:
-        version_quantifier = USE_NEWEST_VERSION[image_name]
-    except KeyError:
-        die_image_not_found()
-
-    sorted_versions = sorted(versions[image_name], key=version_quantifier)
-    latest_version = list(sorted_versions)[-1]
-    image_key = (image_name, latest_version)
-else:
-    image_key = tuple(image_name.split(":"))
-
-try:
-    url = urls[image_key]
-except KeyError:
-    die_image_not_found()
-
-signature_url = "{}.asc".format(url)
-if dry_run:
-    print(url)
-else:
-    utils.plash_exec("import-url", url, signature_url)
+if [[ "$2" = "--dry" ]]; then
+  echo $rootfs
+else
+  exec plash import-url "$rootfs" "$rootfs".asc
+fi
