unit tests pass again

diff --git a/tests/plash-run b/tests/plash-run
--- a/tests/plash-run
+++ b/tests/plash-run
@@ -1,20 +1,44 @@
 set -xeu
-# vim: set filetype=sh:
 
-echo 'TEST: run a program on the base layer of a container'
-plash-build -i busybox
-out=$(plash-run busybox -- echo hellow)
+: run a program on the base layer of a container
+plash-build -i 1
+out=$(plash-run 1 -- echo hellow)
 test "$out" == hellow
 
-echo 'TEST: create a new layer and check that for programs' \
-' the current working directory is mapped'
-newcont=$(plash-build -i busybox --bust-cache)
-cd /tmp
-out=$(plash-run $newcont pwd)
-test "$out" == "/tmp"
+: run something with an layer
+new=$(plash-create 1 true)
+out=$(plash-run $new -- echo hi)
+test "$out" == hi
 
-echo 'TEST: check that exit status get propagaded to the outside'
+: check the current dir is mapped
+cd /tmp
+out=$(plash-run 1 pwd)
+test "$out" == $(pwd)
+cd -
+
+: check that exit status get propagaded to the outside
 set +e
-plash-run busybox sh -c 'exit 42'
+plash-run 1 sh -c 'exit 42'
 test $? -eq 42 || exit 1
 set -e
+
+: check that environment variables are exported to the container
+out=$(MYENV=123 plash-run 1 sh -c 'echo $MYENV')
+test $out = 123
+
+: test a mount
+tmp=$(mktemp)
+plash-run 1 --mount /etc/passwd cat /etc/passwd > $tmp
+cat $tmp
+cmp /etc/passwd $tmp
+
+: test auto build
+plash-run -i 1 --bust-cache -- ls
+
+: mounts get cleanuped
+new=$(plash-create 1 ls)
+before=$(mount | grep "/index/$new" | wc -l)
+plash-run $new --mount default,cgroup ls
+sleep 6 # wait for cleanup
+after=$(mount | grep "index/$new" | wc -l)
+test $before = $after
